using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Avalonia.Input.Platform;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Terrarium.Avalonia.Models.Kanban;
using Terrarium.Avalonia.ViewModels.Core;
using Terrarium.Core.Interfaces.Context;
using Terrarium.Core.Interfaces.Kanban;
using Terrarium.Core.Models.Context;

namespace Terrarium.Avalonia.ViewModels;

/// <summary>
/// A plugin-ready ViewModel for the Kanban board.
/// It observes a central Context Service to stay in sync with the Sidebar selection.
/// </summary>
public partial class KanbanBoardViewModel : ViewModelBase
{
    private readonly IBoardService _boardService;
    private readonly IProjectContextService _contextService;
    
    [ObservableProperty]
    private string _currentWorkspaceId = "solo-workspace";

    [ObservableProperty]
    private string? _currentProjectId;
    
    [ObservableProperty]
    private bool _isDeleteAllConfirmationOpen;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsDetailPanelOpen))]
    [NotifyCanExecuteChangedFor(nameof(DeleteTaskCommand))]
    [NotifyCanExecuteChangedFor(nameof(DeleteSelectedTasksCommand))]
    [NotifyCanExecuteChangedFor(nameof(DeleteAllTasksCommand))]
    private TaskItem? _openedTask;

    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(DeleteSelectedTasksCommand))]
    private int _selectionCount;
    
    public ObservableCollection<Column> Columns { get; set; } = new();
    public ObservableHashSet<string> SelectedTaskIds { get; } = new();

    public bool IsDetailPanelOpen => OpenedTask != null;

    public KanbanBoardViewModel(IBoardService boardService, IProjectContextService contextService)
    {
        _boardService = boardService;
        _contextService = contextService;

        _contextService.ContextChanged += OnContextChanged;

        // Initial load for startup
        _ = LoadDataAsync();
    }

    private void OnContextChanged(ProjectContext context) => ApplyContext(context);

    private void ApplyContext(ProjectContext context)
    {
        _currentWorkspaceId = context.WorkspaceId;
        _currentProjectId = context.ProjectId;
        
        _ = LoadDataAsync();
    
        // Notify UI that properties changed
        OnPropertyChanged(nameof(CurrentWorkspaceId));
        OnPropertyChanged(nameof(CurrentProjectId));
    }
    
    public async Task LoadDataAsync()
    {
        if (string.IsNullOrEmpty(CurrentWorkspaceId) && _contextService.CurrentContext != null)
        {
            CurrentWorkspaceId = _contextService.CurrentContext.WorkspaceId;
            CurrentProjectId = _contextService.CurrentContext.ProjectId;
        }

        if (string.IsNullOrEmpty(CurrentWorkspaceId)) return;

        var boardData = await _boardService.LoadBoardAsync(CurrentWorkspaceId, CurrentProjectId);
    
        Columns.Clear();
        foreach (var colEntity in boardData)
        {
            var columnVm = new Column(colEntity);
            foreach (var taskEntity in colEntity.Tasks) 
            {
                columnVm.Tasks.Add(new TaskItem(taskEntity));
            }
            Columns.Add(columnVm);
        }
    }
    
    partial void OnOpenedTaskChanging(TaskItem? value)
    {
        if (OpenedTask != null)
        {
            _ = SaveTaskAsync(OpenedTask);
        }
    }

    // Property change hooks generated by CommunityToolkit Source Generators
    partial void OnCurrentWorkspaceIdChanged(string value) => _ = LoadDataAsync();
    partial void OnCurrentProjectIdChanged(string? value) => _ = LoadDataAsync();

    [RelayCommand]
    private async Task AddItemAsync(Column targetColumn)
    {
        var newEntity = await _boardService.CreateDefaultTaskEntity(targetColumn.Id, CurrentWorkspaceId, CurrentProjectId);
        await _boardService.AddTaskAsync(newEntity, targetColumn.Id, CurrentWorkspaceId, CurrentProjectId);
        
        var newTask = new TaskItem(newEntity);
        targetColumn.Tasks.Insert(0, newTask);
        OpenedTask = newTask;
    }

    [RelayCommand(CanExecute = nameof(CanDeleteTask))]
    private async Task DeleteTaskAsync()
    {
        if (OpenedTask is not { } taskToDelete) return;

        var sourceColumn = Columns.FirstOrDefault(c => c.Tasks.Contains(taskToDelete));
        if (sourceColumn != null)
        {
            sourceColumn.Tasks.Remove(taskToDelete);
            OpenedTask = null;
            await _boardService.DeleteTaskAsync(taskToDelete.Entity);
        }
    }
    private bool CanDeleteTask() => OpenedTask != null;

    [RelayCommand]
    private async Task SaveTaskCommandAsync() 
    {
        if (OpenedTask != null) await SaveTaskAsync(OpenedTask);
    }

    [RelayCommand]
    private async Task SmartPasteAsync(IClipboard clipboard)
    {
        var text = await clipboard.GetTextAsync();
        if (string.IsNullOrWhiteSpace(text)) return;
        
        var newTasks = await _boardService.ProcessSmartPasteAsync(text, CurrentWorkspaceId, CurrentProjectId);
        foreach (var entity in newTasks)
        {
            var uiColumn = Columns.FirstOrDefault(c => c.Id == entity.ColumnId);
            uiColumn?.Tasks.Add(new TaskItem(entity));
        }
    }

    [RelayCommand]
    private async Task ConfirmDeleteAllAsync()
    {
        IsDeleteAllConfirmationOpen = false;
        await _boardService.WipeBoardAsync();
        foreach (var column in Columns) column.Tasks.Clear();
        OpenedTask = null;
    }

    [RelayCommand(CanExecute = nameof(CanDeleteSelected), AllowConcurrentExecutions = false)]
    private async Task DeleteSelectedTasksAsync()
    {
        var idsToDelete = SelectedTaskIds.ToList();
        if (OpenedTask != null && idsToDelete.Contains(OpenedTask.Id)) OpenedTask = null;
        
        await _boardService.DeleteMultipleTasksAsync(idsToDelete);
        
        foreach (var column in Columns)
        {
            var toRemove = column.Tasks.Where(t => idsToDelete.Contains(t.Id)).ToList();
            foreach (var task in toRemove) column.Tasks.Remove(task);
        }
    
        SelectedTaskIds.Clear();
        SelectionCount = 0;
    }
    private bool CanDeleteSelected() => !IsDetailPanelOpen && SelectionCount > 0;

    [RelayCommand(CanExecute = nameof(CanModifyBoard))]
    private void DeleteAllTasks() => IsDeleteAllConfirmationOpen = true;

    [RelayCommand]
    private void CancelDeleteAll() => IsDeleteAllConfirmationOpen = false;

    private bool CanModifyBoard() => !IsDetailPanelOpen;

    [RelayCommand]
    private void OpenTask(TaskItem task)
    {
        task.IsSelected = true;
        if (!SelectedTaskIds.Contains(task.Id)) SelectedTaskIds.Add(task.Id);
        OpenedTask = task;
        SelectionCount = SelectedTaskIds.Count;
    }

    [RelayCommand]
    private void ToggleTaskSelection(TaskItem task)
    {
        if (IsDetailPanelOpen && OpenedTask?.Id == task.Id) return;

        task.IsSelected = !task.IsSelected;
        if (task.IsSelected) SelectedTaskIds.Add(task.Id);
        else SelectedTaskIds.Remove(task.Id);

        SelectionCount = SelectedTaskIds.Count;
    }

    [RelayCommand(CanExecute = nameof(CanModifyBoard))]
    private void SelectAllTasks()
    {
        SelectedTaskIds.Clear();
        foreach (var task in Columns.SelectMany(c => c.Tasks))
        {
            SelectedTaskIds.Add(task.Id);
            task.IsSelected = true;
        }
        SelectionCount = SelectedTaskIds.Count;
    }

    [RelayCommand]
    private void DeselectAll()
    {
        if (IsDeleteAllConfirmationOpen) return;
        if (IsDetailPanelOpen) { CloseDetails(); return; }

        SelectedTaskIds.Clear();
        foreach (var task in Columns.SelectMany(c => c.Tasks)) task.IsSelected = false;
        SelectionCount = 0;
    }

    public async Task MoveTaskAsync(TaskItem task, Column targetColumn, int index = -1)
    {
        var tasksToMove = task.IsSelected 
            ? Columns.SelectMany(c => c.Tasks).Where(t => t.IsSelected).ToList()
            : new List<TaskItem> { task };

        var ids = tasksToMove.Select(t => t.Id).ToList();
        
        foreach (var t in tasksToMove)
        {
            var sourceCol = Columns.FirstOrDefault(c => c.Tasks.Contains(t));
            sourceCol?.Tasks.Remove(t);
            
            if (index == -1 || index > targetColumn.Tasks.Count)
                targetColumn.Tasks.Add(t);
            else
                targetColumn.Tasks.Insert(index++, t);
        }
        
        await _boardService.MoveTasksWithEconomyAsync(ids, targetColumn.Id, targetColumn.Title, index);
    }

    private async Task SaveTaskAsync(TaskItem task)
    {
        try
        {
            await _boardService.UpdateTaskFromUiAsync(
                task.Entity, 
                task.Title, 
                task.Description, 
                task.Tag, 
                task.Priority,
                task.DueDate
            );
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"Save failed: {ex.Message}");
        }
    }

    public void CloseDetails()
    {
        if (OpenedTask != null)
        {
            OpenedTask.IsSelected = false;
            SelectedTaskIds.Remove(OpenedTask.Id);
            SelectionCount = SelectedTaskIds.Count;
            _ = SaveTaskAsync(OpenedTask);
        }
        OpenedTask = null;
    }
}